// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parnas.Infrastructure.ApplicationDbContext;

#nullable disable

namespace Parnas.Infrastructure.Migrations
{
    [DbContext(typeof(ParnasDbContext))]
    partial class ParnasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parnas.Domain.Entities.Accessories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AntiGhosting")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Lighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Microphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutPut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CaseFanSpeedController")
                        .HasColumnType("bit");

                    b.Property<string>("CaseLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseUSBType_CPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FancaseLightingController")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadPhoneOutPut")
                        .HasColumnType("bit");

                    b.Property<string>("Inch2_5DriveBay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inch3_5DriveBay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Lighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSizeOfCoolerBackPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSizeOfCoolerCeilingPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSizeOfCoolerFrontPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumCPUCoolerHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumLengthOfGraphicCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MicrophoneInput")
                        .HasColumnType("bit");

                    b.Property<string>("NumberOf120mmInstallableFans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFanInstalledInCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFansThatCanBeInstalledInCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFansThatCanBeInstalledInTheFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFansThatCanBeInstalledinTheCeiling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFansThatCanBeInstalledonTheBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfInstalledFansIs140mm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofPowerSuppliesThatCanBeInstalled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofUSBPortsIs3Cases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupplyInstallationLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ComputerMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackLight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayAspectRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayImagePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HdmiImagePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MonitorTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonitorUserClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PannelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerConsumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RotationCapability")
                        .HasColumnType("bit");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusContrast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsbPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VesaSupport")
                        .HasColumnType("bit");

                    b.Property<string>("VisualAngle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Cooling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AMDSocketSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolingFanRotationSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolingPipeLenght")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FanConnection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FanLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntelSocketSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaximumAirFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfCoolingFans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PumpRotationSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadiatorDimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadiatorMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfCoolingFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfProccesorBlock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coolings");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseFerequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoostFerequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUMaxHdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUMemoryTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUMonitorCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CachLevel2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CachLevel3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Generation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicProccesor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicProccesorFerequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicProccesorModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HDDFerequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCIExpressCPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Packaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCounsumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Socket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.FanCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseFanNoiseLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CaseFanSpeedController")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FanCaseController")
                        .HasColumnType("bit");

                    b.Property<string>("FanCaseLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FanCaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FanCaseUsageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LightingControllerFanCase")
                        .HasColumnType("bit");

                    b.Property<string>("MaximumCaseAirFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RatiotionSpeedOfTheCaseFan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FanCases");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Gaming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeepCool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Graphic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MotherBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Gamings");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseFerequencyOfTheGraphicsCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoostFerequensyOfTheGraphicsCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CudaCore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectXInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayPortOutputOfTheGraphicCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FullHdSupport")
                        .HasColumnType("bit");

                    b.Property<string>("GPUManuFacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicCardModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicCardProccesorGeneration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GraphicsCardCooler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HDCPSupport")
                        .HasColumnType("bit");

                    b.Property<string>("HdmiOutPutOfTheGraphicCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterfaceBandWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("K4Support")
                        .HasColumnType("bit");

                    b.Property<bool>("K8Support")
                        .HasColumnType("bit");

                    b.Property<string>("Lighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemorySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemorySpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfGraphicCardFans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenGLInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PciExpressGeneration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecommendedPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("GraphicCards");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.HDD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardDiskCachMemory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardDrivePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RotationSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheAppearanceOfTheHardDrive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("HDDs");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.MotherBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppearanceOfTheMotherBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("BluetoothVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPUPowerConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HdmiOutputOfTheMotherBoard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("M2Slot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainPowerConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumMemorySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemorySlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherBoardDisplayPortOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherBoardMemoryTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfSataPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCIExperssX16Generation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PCIExperssX16Slot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProccesorSocket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaidSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoundChipset")
                        .HasColumnType("bit");

                    b.Property<string>("SupportedProccesor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmpSupport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MotherBoards");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ATX3Standard")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Current33V")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Current5VSBV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EighteenPlusCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First12Current")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NominalPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P4P4PinConnection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin24Connection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinPcieConnection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinSataConnector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plus5VCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupplyConnectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupplyFanLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupplyFanSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProtectionStandards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("v12VoltCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Powers");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductImages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ferequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NumberOfModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RamCooler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RomeLighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalMemorySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfRamMemory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeOfEachModules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.SSD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Longevity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReadingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSDAppearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSDInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSDMemoryTechnology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSDPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WritingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SSDs");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Case+CaseImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("CaseImage_ProductImageId");

                    b.HasIndex("CaseId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("CaseImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ComputerMonitor+ComputerMonitorImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("ComputerMonitorId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("ComputerMonitorImage_ProductImageId");

                    b.HasIndex("ComputerMonitorId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("ComputerMonitorImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Cooling+CoolingImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("CoolingId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("CoolingImage_ProductImageId");

                    b.HasIndex("CoolingId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("CoolingImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.CPU+CPUImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("CPUId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("CPUImage_ProductImageId");

                    b.HasIndex("CPUId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("CPUImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.FanCase+FanCaseImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("FanCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("FanCaseImage_ProductImageId");

                    b.HasIndex("FanCaseId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("FanCaseImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Gaming+GamingImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("GamingId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("GamingImage_ProductImageId");

                    b.HasIndex("GamingId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("GamingImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCard+GraphicCardImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("GraphicCardId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("GraphicCardImage_ProductImageId");

                    b.Property<int?>("ProductImageId1")
                        .HasColumnType("int");

                    b.HasIndex("GraphicCardId");

                    b.HasIndex("ProductImageId");

                    b.HasIndex("ProductImageId1");

                    b.HasDiscriminator().HasValue("GraphicCardImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCardImagr", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("AccessoryId")
                        .HasColumnType("int");

                    b.HasIndex("AccessoryId");

                    b.HasDiscriminator().HasValue("GraphicCardImagr");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.HDD+HDDImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("HDDId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("HDDImage_ProductImageId");

                    b.HasIndex("HDDId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("HDDImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.MotherBoard+MotherBoardImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("MotherBoardId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("MotherBoardImage_ProductImageId");

                    b.HasIndex("MotherBoardId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("MotherBoardImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Power+PowerImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int>("PowerId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int");

                    b.HasIndex("PowerId");

                    b.HasIndex("ProductImageId");

                    b.HasDiscriminator().HasValue("PowerImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Ram+RamImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("RamImage_ProductImageId");

                    b.Property<int>("RamId")
                        .HasColumnType("int");

                    b.HasIndex("ProductImageId");

                    b.HasIndex("RamId");

                    b.HasDiscriminator().HasValue("RamImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.SSD+SSDImage", b =>
                {
                    b.HasBaseType("Parnas.Domain.Entities.ProductImage");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int")
                        .HasColumnName("SSDImage_ProductImageId");

                    b.Property<int>("SSDId")
                        .HasColumnType("int");

                    b.HasIndex("ProductImageId");

                    b.HasIndex("SSDId");

                    b.HasDiscriminator().HasValue("SSDImage");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Accessories", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Accessories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Case", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Cases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Category", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ComputerMonitor", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("ComputerMonitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Cooling", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Coolings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.CPU", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("CPUs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.FanCase", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("FanCases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Gaming", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Gamings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCard", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("GraphicCards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.HDD", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("HDDs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.MotherBoard", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("MotherBoards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Power", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Powers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Ram", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("Rams")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.SSD", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Category", "Category")
                        .WithMany("SSDs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Case+CaseImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Case", "Case")
                        .WithMany("ImageList")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("CaseImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ComputerMonitor+ComputerMonitorImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.ComputerMonitor", "ComputerMonitor")
                        .WithMany("ImageList")
                        .HasForeignKey("ComputerMonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("ComputerMonitorImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("ComputerMonitor");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Cooling+CoolingImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Cooling", "Cooling")
                        .WithMany("ImageList")
                        .HasForeignKey("CoolingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("CoolingImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("Cooling");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.CPU+CPUImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.CPU", "CPU")
                        .WithMany("ImageList")
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("CPUImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("CPU");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.FanCase+FanCaseImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.FanCase", "FanCase")
                        .WithMany("ImageList")
                        .HasForeignKey("FanCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("FanCaseImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("FanCase");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Gaming+GamingImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Gaming", "Gaming")
                        .WithMany("ImageList")
                        .HasForeignKey("GamingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("GamingImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("Gaming");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCard+GraphicCardImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.GraphicCard", "GraphicCard")
                        .WithMany("ImageList")
                        .HasForeignKey("GraphicCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("AccessoryImageList")
                        .HasForeignKey("ProductImageId");

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("GraphicCardImageList")
                        .HasForeignKey("ProductImageId1");

                    b.Navigation("GraphicCard");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCardImagr", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Accessories", "Accessories")
                        .WithMany("ImageList")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.HDD+HDDImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.HDD", "HDD")
                        .WithMany("ImageList")
                        .HasForeignKey("HDDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("HDDImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("HDD");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.MotherBoard+MotherBoardImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.MotherBoard", "MotherBoard")
                        .WithMany("ImageList")
                        .HasForeignKey("MotherBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("MotherBoardImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("MotherBoard");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Power+PowerImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.Power", "Power")
                        .WithMany("ImageList")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("PowerImageList")
                        .HasForeignKey("ProductImageId");

                    b.Navigation("Power");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Ram+RamImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("RamImageList")
                        .HasForeignKey("ProductImageId");

                    b.HasOne("Parnas.Domain.Entities.Ram", "Ram")
                        .WithMany("ImageList")
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.SSD+SSDImage", b =>
                {
                    b.HasOne("Parnas.Domain.Entities.ProductImage", null)
                        .WithMany("SSDImageList")
                        .HasForeignKey("ProductImageId");

                    b.HasOne("Parnas.Domain.Entities.SSD", "SSD")
                        .WithMany("ImageList")
                        .HasForeignKey("SSDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SSD");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Accessories", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Case", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Category", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("CPUs");

                    b.Navigation("Cases");

                    b.Navigation("ComputerMonitors");

                    b.Navigation("Coolings");

                    b.Navigation("FanCases");

                    b.Navigation("Gamings");

                    b.Navigation("GraphicCards");

                    b.Navigation("HDDs");

                    b.Navigation("MotherBoards");

                    b.Navigation("Powers");

                    b.Navigation("Rams");

                    b.Navigation("SSDs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ComputerMonitor", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Cooling", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.CPU", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.FanCase", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Gaming", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.GraphicCard", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.HDD", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.MotherBoard", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Power", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.ProductImage", b =>
                {
                    b.Navigation("AccessoryImageList");

                    b.Navigation("CPUImageList");

                    b.Navigation("CaseImageList");

                    b.Navigation("ComputerMonitorImageList");

                    b.Navigation("CoolingImageList");

                    b.Navigation("FanCaseImageList");

                    b.Navigation("GamingImageList");

                    b.Navigation("GraphicCardImageList");

                    b.Navigation("HDDImageList");

                    b.Navigation("MotherBoardImageList");

                    b.Navigation("PowerImageList");

                    b.Navigation("RamImageList");

                    b.Navigation("SSDImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.Ram", b =>
                {
                    b.Navigation("ImageList");
                });

            modelBuilder.Entity("Parnas.Domain.Entities.SSD", b =>
                {
                    b.Navigation("ImageList");
                });
#pragma warning restore 612, 618
        }
    }
}
